spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/maintainlydb
    username: postgres
    password: test
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] [%X{correlationId:-none}] [org:%X{organizationId:-none}] %-5level %logger{36} - %msg%n"
