ALTER TABLE organizations
    ADD COLUMN created_at TIMESTAMP
        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP
        NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE app_users
    ADD COLUMN created_at TIMESTAMP
        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP
        NOT NULL DEFAULT CURRENT_TIMESTAMP;
